import { launch, makeContext, signIn, shot, settle, VIEWPORTS, BASE } from './lib.mjs';
const browser = await launch();
const ctx = await makeContext(browser, { viewport: VIEWPORTS.laptop });
const page = await ctx.newPage();
await page.goto(`${BASE}/api/dev/sign-in?as=learner&reset=1&returnTo=%2Ftoday`, { waitUntil: 'domcontentloaded' });
await settle(page, 2000);
const q = await (await page.request.get(`${BASE}/api/review/queue?limit=200`)).json();
const ins = await (await page.request.get(`${BASE}/api/stats/insights`)).json();
console.log('Today / review queue total (cards due today):', q.total);
console.log('Insights AHEAD first bucket (today):', ins.forecast[0]);
console.log('Insights AHEAD sum:', ins.forecast.reduce((a,b)=>a+b.count,0));
console.log('Insights CARDS new:', ins.cards.new, '| total:', ins.cards.total);
const rounds = await (await page.request.get(`${BASE}/api/review/rounds`)).json();
console.log('Today rounds (new tile):', JSON.stringify(rounds));
await page.goto(`${BASE}/today`, { waitUntil: 'domcontentloaded' }); await settle(page, 1200);
await shot(page, 'bug-mismatch/today', { fullPage: false });
await page.goto(`${BASE}/insights`, { waitUntil: 'domcontentloaded' }); await settle(page, 1200);
await shot(page, 'bug-mismatch/insights', { fullPage: false });
await browser.close();
