#!/usr/bin/env node

// The phone wears the product's palette, type scale and radii, read from apps/web's styles.css.
// Writes src/theme.gen.css for Uniwind and src/theme/tokens.gen.ts for what cannot read CSS:
// the lantern's SVG, native headers and the widget, which runs in its own runtime.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { block, paletteFrom } from "../../../scripts/check-design-docs.mjs";

const root = resolve(import.meta.dirname, "..");
const css = readFileSync(resolve(root, "../web/src/client/styles.css"), "utf8");

const palette = paletteFrom(css);
const light = palette.filter(([name]) => !name.startsWith("dark-"));
const dark = palette
  .filter(([name]) => name.startsWith("dark-"))
  .map(([name, hex]) => [name.slice(5), hex]);

const theme = block(css, "@theme inline");
// RN has no root font size, so a rem step becomes its px value at the 16 px default.
const px = (value) => (value.endsWith("rem") ? `${Number.parseFloat(value) * 16}px` : value);
const scale = Object.entries(theme)
  .filter(([name]) => /^(text|radius)-/.test(name))
  .map(([name, value]) => `  --${name}: ${name.endsWith("line-height") ? value : px(value)};`);

const variables = (pairs) => pairs.map(([name, hex]) => `      --color-${name}: ${hex};`);

const out = `/* Generated by scripts/tokens.mjs from apps/web/src/client/styles.css. Do not edit. */

@theme {
  --font-sans: "Onest";
${scale.join("\n")}
}

@layer theme {
  :root {
    @variant light {
${variables(light).join("\n")}
    }
    @variant dark {
${variables(dark).join("\n")}
    }
  }
}
`;
writeFileSync(resolve(root, "src/theme.gen.css"), out);

const object = (pairs) =>
  `{\n${pairs.map(([name, hex]) => `    ${JSON.stringify(name)}: ${JSON.stringify(hex)},`).join("\n")}\n  }`;
writeFileSync(
  resolve(root, "src/theme/tokens.gen.ts"),
  `// Generated by scripts/tokens.mjs from apps/web/src/client/styles.css. Do not edit.

export const palette = {
  light: ${object(light)},
  dark: ${object(dark)},
} as const;

export type Colour = keyof typeof palette.light;
`,
);
console.log(`Wrote ${light.length} colours per room.`);
