import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

/**
 * The cards the landing hand deals. Each is something a stranger would be glad to know, and the
 * spread is the argument that Lymi holds more than vocabulary. Audio lives at
 * `/audio/hand/<id>.mp3`; run `pnpm --filter @lymi/site hand:audio` after changing a term.
 */
export interface HandCard {
  /** Stable, ASCII, and the audio file's name. */
  id: string;
  /** Where the card is from, shown above the term. A language names itself, untranslated. */
  source: string | MessageDescriptor;
  kind: MessageDescriptor;
  /** BCP 47 tag of the term, used for `lang` and for the voice. */
  language: string;
  term: string;
  /** A reading for a term in a script the visitor may not read. */
  reading?: string;
  pronunciation?: string;
  meaning: MessageDescriptor;
  /** One line that makes the term stick: where it comes from, or when it is said. */
  note: MessageDescriptor;
}

const noun = msg`noun`;
const phrase = msg`phrase`;
const word = msg`word`;
const idea = msg`idea`;

export const HAND_CARDS: HandCard[] = [
  {
    id: "kalsarikannit",
    source: "Suomi",
    kind: noun,
    language: "fi",
    term: "kalsarikännit",
    pronunciation: "/ˈkɑlsɑriˌkænːit/",
    meaning: msg`Drinking at home, alone, in your underwear`,
    note: msg`Finnish has a word for a night with no plans to go out.`,
  },
  {
    id: "sisu",
    source: "Suomi",
    kind: noun,
    language: "fi",
    term: "sisu",
    pronunciation: "/ˈsisu/",
    meaning: msg`Stubborn grit; carrying on when it gets hard`,
    note: msg`Finns often name it as part of the national character.`,
  },
  {
    id: "jaaaar",
    source: "Eesti",
    kind: noun,
    language: "et",
    term: "jäääär",
    pronunciation: "/ˈjæːæːr/",
    meaning: msg`The edge of the ice`,
    note: msg`Ice, jää, plus edge, äär: four ä in a row.`,
  },
  {
    id: "komorebi",
    source: "日本語",
    kind: noun,
    language: "ja",
    term: "木漏れ日",
    reading: "こもれび · komorebi",
    pronunciation: "/ko.mo.ɾe.bi/",
    meaning: msg`Sunlight filtering through leaves`,
    note: msg`Written with the characters for tree, leak and sun.`,
  },
  {
    id: "itadakimasu",
    source: "日本語",
    kind: phrase,
    language: "ja",
    term: "いただきます",
    reading: "itadakimasu",
    pronunciation: "/i.ta.da.ki.ma.sɯ̥/",
    meaning: msg`Said before eating: “I humbly receive”`,
    note: msg`A thank-you to everyone who brought the food to the table.`,
  },
  {
    id: "tsundoku",
    source: "日本語",
    kind: noun,
    language: "ja",
    term: "積ん読",
    reading: "つんどく · tsundoku",
    pronunciation: "/tsɯn.do.kɯ/",
    meaning: msg`Buying books and letting them pile up unread`,
    note: msg`A pun on tsunde oku, to leave piled, and doku, reading.`,
  },
  {
    id: "sobremesa",
    source: "Español",
    kind: noun,
    language: "es",
    term: "sobremesa",
    pronunciation: "/soβɾeˈmesa/",
    meaning: msg`Staying at the table to talk after a meal`,
    note: msg`Sobre, over, plus mesa, table. It can outlast the meal.`,
  },
  {
    id: "saudade",
    source: "Português",
    kind: noun,
    language: "pt-PT",
    term: "saudade",
    pronunciation: "/sɐwˈðaðɨ/",
    meaning: msg`A longing for someone or something that is gone`,
    note: msg`Fado, Portugal’s mournful song, is built on it.`,
  },
  {
    id: "schnapsidee",
    source: "Deutsch",
    kind: noun,
    language: "de",
    term: "Schnapsidee",
    pronunciation: "/ˈʃnapsʔiˌdeː/",
    meaning: msg`An idea that only sounds brilliant after a few drinks`,
    note: msg`Schnaps, spirits, plus Idee, idea.`,
  },
  {
    id: "feierabend",
    source: "Deutsch",
    kind: noun,
    language: "de",
    term: "Feierabend",
    pronunciation: "/ˈfaɪ̯ɐˌʔaːbn̩t/",
    meaning: msg`Clocking off, and the free evening that follows`,
    note: msg`“Schönen Feierabend!” wishes someone a good evening off.`,
  },
  {
    id: "avoir-la-flemme",
    source: "Français",
    kind: phrase,
    language: "fr",
    term: "avoir la flemme",
    pronunciation: "/a.vwaʁ la flɛm/",
    meaning: msg`To not be able to be bothered`,
    note: msg`“J’ai la flemme” is the whole excuse.`,
  },
  {
    id: "magari",
    source: "Italiano",
    kind: word,
    language: "it",
    term: "magari",
    pronunciation: "/maˈɡaːri/",
    meaning: msg`If only; maybe; I wish`,
    note: msg`Asked whether you’d like to win the lottery: “Magari!”`,
  },
  {
    id: "gezellig",
    source: "Nederlands",
    kind: word,
    language: "nl",
    term: "gezellig",
    pronunciation: "/ɣəˈzɛləx/",
    meaning: msg`Cosy and convivial; good company`,
    note: msg`A café, an evening or a person can all be gezellig.`,
  },
  {
    id: "lagom",
    source: "Svenska",
    kind: word,
    language: "sv",
    term: "lagom",
    pronunciation: "/ˈlɑ̂ːɡɔm/",
    meaning: msg`Just the right amount: not too much, not too little`,
    note: msg`Swedes use it for coffee and working hours alike.`,
  },
  {
    id: "nunchi",
    source: "한국어",
    kind: noun,
    language: "ko",
    term: "눈치",
    reading: "nunchi",
    pronunciation: "/nun.tɕʰi/",
    meaning: msg`The knack of reading the room`,
    note: msg`Quick nunchi means sensing a mood before anyone says a word.`,
  },
  {
    id: "smachnoho",
    source: "Українська",
    kind: phrase,
    language: "uk",
    term: "Смачного!",
    reading: "smachnoho",
    pronunciation: "/smɑt͡ʃˈnɔɦɔ/",
    meaning: msg`Enjoy your meal!`,
    note: msg`Said to anyone about to eat, the way French says bon appétit.`,
  },
  {
    id: "kolay-gelsin",
    source: "Türkçe",
    kind: phrase,
    language: "tr",
    term: "Kolay gelsin",
    pronunciation: "/koˈlaj ɟelˈsin/",
    meaning: msg`“May it come easy”, said to someone at work`,
    note: msg`For a cashier, a builder, or a friend who is studying.`,
  },
  {
    id: "mamahuhu",
    source: "中文",
    kind: phrase,
    language: "zh-CN",
    term: "马马虎虎",
    reading: "mǎmǎhūhū",
    meaning: msg`So-so; careless`,
    note: msg`Literally “horse horse tiger tiger”.`,
  },
  {
    id: "thetta-reddast",
    source: "Íslenska",
    kind: phrase,
    language: "is",
    term: "Þetta reddast",
    pronunciation: "/ˈθɛʰta ˈrɛtːast/",
    meaning: msg`It will all work out`,
    note: msg`Often called Iceland’s unofficial motto.`,
  },
  {
    id: "jugaad",
    source: "हिन्दी",
    kind: noun,
    language: "hi",
    term: "जुगाड़",
    reading: "jugaad",
    pronunciation: "/dʒʊˈɡaːɽ/",
    meaning: msg`A clever fix made from whatever is at hand`,
    note: msg`Tape, a spare part and some nerve.`,
  },
  {
    id: "zeigarnik-effect",
    source: msg`Psychology`,
    kind: idea,
    language: "en",
    term: "Zeigarnik effect",
    pronunciation: "/zaɪˈɡɑːnɪk/",
    meaning: msg`Unfinished tasks stay on your mind more than finished ones`,
    note: msg`It’s why a half-read chapter keeps nagging at you.`,
  },
  {
    id: "spacing-effect",
    source: msg`Psychology`,
    kind: idea,
    language: "en",
    term: "spacing effect",
    meaning: msg`Reviews spread over days stick better than the same reviews crammed together`,
    note: msg`Lymi schedules every card around it.`,
  },
  {
    id: "baader-meinhof",
    source: msg`Psychology`,
    kind: idea,
    language: "en",
    term: "Baader–Meinhof phenomenon",
    pronunciation: "/ˈbɑːdə ˈmaɪnhɒf/",
    meaning: msg`After you learn something new, you start noticing it everywhere`,
    note: msg`Also called the frequency illusion.`,
  },
  {
    id: "sunk-cost-fallacy",
    source: msg`Economics`,
    kind: idea,
    language: "en",
    term: "sunk cost fallacy",
    meaning: msg`Sticking with something because of what you have already put in`,
    note: msg`Sitting through a bad film because you paid for the ticket.`,
  },
  {
    id: "goodharts-law",
    source: msg`Economics`,
    kind: idea,
    language: "en",
    term: "Goodhart’s law",
    meaning: msg`When a measure becomes a target, it stops being a good measure`,
    note: msg`Reward lines of code, and the code gets longer.`,
  },
  {
    id: "regression-to-the-mean",
    source: msg`Statistics`,
    kind: idea,
    language: "en",
    term: "regression to the mean",
    meaning: msg`An extreme result is usually followed by a more ordinary one`,
    note: msg`A brilliant first round rarely repeats in the second.`,
  },
  {
    id: "benfords-law",
    source: msg`Statistics`,
    kind: idea,
    language: "en",
    term: "Benford’s law",
    meaning: msg`In many real data sets, about 30% of numbers start with a 1`,
    note: msg`Auditors use it to spot figures that were made up.`,
  },
  {
    id: "hysteresis",
    source: msg`Physics`,
    kind: idea,
    language: "en",
    term: "hysteresis",
    pronunciation: "/ˌhɪstəˈriːsɪs/",
    meaning: msg`When the output depends on the history of the input`,
    note: msg`A thermostat that turns on at 19° and off at 21°.`,
  },
  {
    id: "zugzwang",
    source: msg`Chess`,
    kind: idea,
    language: "de",
    term: "zugzwang",
    pronunciation: "/ˈtsuːkˌtsvaŋ/",
    meaning: msg`Any move you make makes your position worse`,
    note: msg`The player would pass, if chess allowed it.`,
  },
  {
    id: "mise-en-place",
    source: msg`Cooking`,
    kind: idea,
    language: "fr",
    term: "mise en place",
    pronunciation: "/miz‿ɑ̃ plas/",
    meaning: msg`Everything prepped and to hand before you start`,
    note: msg`French for “putting in place”.`,
  },
  {
    id: "maillard-reaction",
    source: msg`Cooking`,
    kind: idea,
    language: "en",
    term: "Maillard reaction",
    pronunciation: "/maɪˈjɑːd/",
    meaning: msg`The browning that gives seared, baked and toasted food its flavour`,
    note: msg`Sugars and amino acids reacting in the heat.`,
  },
  {
    id: "chestertons-fence",
    source: msg`Philosophy`,
    kind: idea,
    language: "en",
    term: "Chesterton’s fence",
    meaning: msg`Don’t take down a fence until you know why it was put up`,
    note: msg`From G. K. Chesterton’s 1929 book The Thing.`,
  },
  {
    id: "occams-razor",
    source: msg`Philosophy`,
    kind: idea,
    language: "en",
    term: "Occam’s razor",
    pronunciation: "/ˈɒkəmz ˈreɪzə/",
    meaning: msg`Prefer the explanation that needs the fewest assumptions`,
    note: msg`Named after William of Ockham, a 14th-century friar.`,
  },
  {
    id: "habeas-corpus",
    source: msg`Law`,
    kind: idea,
    language: "en",
    term: "habeas corpus",
    pronunciation: "/ˈheɪbiəs ˈkɔːpəs/",
    meaning: msg`The right to be brought before a judge rather than held without charge`,
    note: msg`Latin for “you shall have the body”.`,
  },
  {
    id: "affordance",
    source: msg`Design`,
    kind: idea,
    language: "en",
    term: "affordance",
    meaning: msg`What an object’s shape tells you to do with it`,
    note: msg`A flat plate on a door says push; a handle says pull.`,
  },
  {
    id: "chekhovs-gun",
    source: msg`Writing`,
    kind: idea,
    language: "en",
    term: "Chekhov’s gun",
    pronunciation: "/ˈtʃɛkɒfs/",
    meaning: msg`If a story shows a gun early on, it should go off later`,
    note: msg`Every detail in a story should earn its place.`,
  },
  {
    id: "rubber-duck-debugging",
    source: msg`Programming`,
    kind: idea,
    language: "en",
    term: "rubber duck debugging",
    meaning: msg`Explaining your code aloud, line by line, until the bug shows itself`,
    note: msg`The duck never answers. It doesn’t need to.`,
  },
  {
    id: "petrichor",
    source: msg`Nature`,
    kind: idea,
    language: "en",
    term: "petrichor",
    pronunciation: "/ˈpɛtrɪkɔː/",
    meaning: msg`The earthy smell of rain on dry ground`,
    note: msg`Named by two Australian scientists in 1964.`,
  },
  {
    id: "mycorrhiza",
    source: msg`Biology`,
    kind: idea,
    language: "en",
    term: "mycorrhiza",
    pronunciation: "/ˌmaɪkəˈraɪzə/",
    meaning: msg`A partnership between fungi and plant roots, trading water for sugar`,
    note: msg`Most land plants have one.`,
  },
  {
    id: "syncopation",
    source: msg`Music`,
    kind: idea,
    language: "en",
    term: "syncopation",
    pronunciation: "/ˌsɪŋkəˈpeɪʃn̩/",
    meaning: msg`Accents that land between the beats`,
    note: msg`The push behind ragtime, funk and reggae.`,
  },
];
